cache:
  paths:
    - node_modules/
    - .npm/

stages:
  - code_scan
  - build

variables:
  PACKAGE_VALUE_FILE:
    description: "FILE TYPE VARIABLE: content for value.json, if set, ignore all belowing values"
  PACKAGE_ID:
    description: "The package ID for shipping package."
    value: "raccoon"
  PACKAGE_NAME:
    description: "The package name for shipping package."
    value: "Raccoon"
  PACKAGE_TYPE:
    description: "The package type for shipping package, Standard/Enterprise"
    value: "Standard"
    options:
      - "Standard"
      - "Enterprise"
  API_TYPE:
    description: "API type"
    value: "Raccoon"
    options:
      - "Raccoon"
      - "TGI"
  BASEURL:
    description: "The base URL path of backend"
    value: "https://raccoon.sensetime.com"

code_scan:
  image: registry.sensetime.com/security/codescan:latest
  stage: code_scan
  script:
    - sonar_full_scan.sh
  tags:
    - k8s

build_package:
  stage: build
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - npm install --prefix ./scripts minimist
    - node ./scripts/render_manifest.js --packageValueFile="$PACKAGE_VALUE_FILE" --packageId="$PACKAGE_ID" --packageName="$PACKAGE_NAME" --packageType="$PACKAGE_TYPE" --apiType="$API_TYPE" --baseUrl="$BASEURL"
    - npm install
    - vsce package -o $PACKAGE_ID-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA.vsix
  artifacts:
    paths:
      - ./$PACKAGE_ID-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA.vsix
    expire_in: 1 week
  tags:
    - copilot-nv-tag