/* eslint-disable @typescript-eslint/naming-convention */

export const supportedLanguages: { [key: string]: string } = {
  "bat": "Windows Bat",
  "clojure": "Clojure",
  "coffeescript": "Coffeescript",
  "c": "C",
  "cpp": "C++",
  "csharp": "C#",
  "dockercompose": "Compose",
  "css": "CSS",
  "cuda-cpp": "CUDA C++",
  "diff": "Diff",
  "dockerfile": "Dockerfile",
  "fsharp": "F#",
  "go": "Go",
  "groovy": "Groovy",
  "handlebars": "Handlebars",
  "haml": "Haml",
  "html": "HTML",
  "ini": "Ini",
  "java": "Java",
  "javascript": "JavaScript",
  "javascriptreact": "JavaScript JSX",
  "jsx": "JavaScript JSX",
  "json": "JSON",
  "jsonc": "JSON with Comments",
  "latex": "LaTeX",
  "less": "Less",
  "lua": "Lua",
  "makefile": "Makefile",
  "markdown": "Markdown",
  "objective-c": "Objective-C",
  "objective-cpp": "Objective-C++",
  "perl": "Perl",
  "perl6": "Perl",
  "php": "PHP",
  "powershell": "PowerShell",
  "pug": "Pug",
  "jade": "Pug",
  "python": "Python",
  "r": "R",
  "razor": "Razor",
  "ruby": "Ruby",
  "rust": "Rust",
  "scss": "SCSS",
  "shaderlab": "ShaderLab",
  "shellscript": "Shell Script",
  "slim": "Slim",
  "sql": "SQL",
  "stylus": "Stylus",
  "swift": "Swift",
  "typescript": "TypeScript",
  "typescriptreact": "TypeScript JSX",
  "tex": "TeX",
  "vb": "Visual Basic",
  "vue": "Vue",
  "vue-html": "Vue HTML",
  "xml": "XML",
  "xsl": "XSL",
  "yaml": "YAML",
};

