/* eslint-disable @typescript-eslint/naming-convention */

export const supportedLanguages: { [key: string]: { displayName: string; singleLineCommentPrefix: string } } = {
  "bat": { displayName: "Windows Bat", singleLineCommentPrefix: "::" },
  "clojure": { displayName: "Clojure", singleLineCommentPrefix: ";;" },
  "coffeescript": { displayName: "Coffeescript", singleLineCommentPrefix: "#" },
  "c": { displayName: "C", singleLineCommentPrefix: "//" },
  "cpp": { displayName: "C++", singleLineCommentPrefix: "//" },
  "csharp": { displayName: "C#", singleLineCommentPrefix: "//" },
  "dockercompose": { displayName: "Compose", singleLineCommentPrefix: "#" },
  "css": { displayName: "CSS", singleLineCommentPrefix: "" },
  "cuda-cpp": { displayName: "CUDA C++", singleLineCommentPrefix: "//" },
  "diff": { displayName: "Diff", singleLineCommentPrefix: "" },
  "dockerfile": { displayName: "Dockerfile", singleLineCommentPrefix: "#" },
  "fsharp": { displayName: "F#", singleLineCommentPrefix: "//" },
  "go": { displayName: "Go", singleLineCommentPrefix: "//" },
  "groovy": { displayName: "Groovy", singleLineCommentPrefix: "//" },
  "handlebars": { displayName: "Handlebars", singleLineCommentPrefix: "" },
  "haml": { displayName: "Haml", singleLineCommentPrefix: "" },
  "html": { displayName: "HTML", singleLineCommentPrefix: "" },
  "ini": { displayName: "Ini", singleLineCommentPrefix: ";" },
  "java": { displayName: "Java", singleLineCommentPrefix: "//" },
  "javascript": { displayName: "JavaScript", singleLineCommentPrefix: "//" },
  "javascriptreact": { displayName: "JavaScript JSX", singleLineCommentPrefix: "//" },
  "jsx": { displayName: "JavaScript JSX", singleLineCommentPrefix: "//" },
  "json": { displayName: "JSON", singleLineCommentPrefix: "" },
  "jsonc": { displayName: "JSON with Comments", singleLineCommentPrefix: "//" },
  "latex": { displayName: "LaTeX", singleLineCommentPrefix: "%" },
  "less": { displayName: "Less", singleLineCommentPrefix: "" },
  "lua": { displayName: "Lua", singleLineCommentPrefix: "--" },
  "makefile": { displayName: "Makefile", singleLineCommentPrefix: "#" },
  "markdown": { displayName: "Markdown", singleLineCommentPrefix: "" },
  "objective-c": { displayName: "Objective-C", singleLineCommentPrefix: "//" },
  "objective-cpp": { displayName: "Objective-C++", singleLineCommentPrefix: "//" },
  "perl": { displayName: "Perl", singleLineCommentPrefix: "#" },
  "perl6": { displayName: "Perl", singleLineCommentPrefix: "#" },
  "php": { displayName: "PHP", singleLineCommentPrefix: "#" },
  "powershell": { displayName: "PowerShell", singleLineCommentPrefix: "#" },
  "pug": { displayName: "Pug", singleLineCommentPrefix: "//" },
  "jade": { displayName: "Pug", singleLineCommentPrefix: "//" },
  "python": { displayName: "Python", singleLineCommentPrefix: "#" },
  "r": { displayName: "R", singleLineCommentPrefix: "#" },
  "razor": { displayName: "Razor", singleLineCommentPrefix: "" },
  "ruby": { displayName: "Ruby", singleLineCommentPrefix: "#" },
  "rust": { displayName: "Rust", singleLineCommentPrefix: "" },
  "scss": { displayName: "SCSS", singleLineCommentPrefix: "" },
  "shaderlab": { displayName: "ShaderLab", singleLineCommentPrefix: "//" },
  "shellscript": { displayName: "Shell Script", singleLineCommentPrefix: "#" },
  "slim": { displayName: "Slim", singleLineCommentPrefix: "" },
  "sql": { displayName: "SQL", singleLineCommentPrefix: "--" },
  "stylus": { displayName: "Stylus", singleLineCommentPrefix: "//" },
  "swift": { displayName: "Swift", singleLineCommentPrefix: "//" },
  "typescript": { displayName: "TypeScript", singleLineCommentPrefix: "//" },
  "typescriptreact": { displayName: "TypeScript JSX", singleLineCommentPrefix: "//" },
  "tex": { displayName: "TeX", singleLineCommentPrefix: "%" },
  "vb": { displayName: "Visual Basic", singleLineCommentPrefix: "'" },
  "vue": { displayName: "Vue", singleLineCommentPrefix: "" },
  "vue-html": { displayName: "Vue HTML", singleLineCommentPrefix: "" },
  "xml": { displayName: "XML", singleLineCommentPrefix: "" },
  "xsl": { displayName: "XSL", singleLineCommentPrefix: "" },
  "yaml": { displayName: "YAML", singleLineCommentPrefix: "#" },
};

